package org.dljl.entity;

import java.time.LocalDateTime;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class Appointment {

  private Long appointmentId; // Auto-generated by the database
  private Long providerId; // Unique to each client
  private Long userId;
  private LocalDateTime startDateTime;
  private LocalDateTime endDateTime;
  private String status;
  private String serviceType;
  private String comments;

}
