package org.dljl.entity;

import java.time.LocalDateTime;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents an appointment scheduled between a provider and a user. This entity includes details
 * about the appointment such as the ID, the participants, the start and end times, status, and
 * additional comments.
 *
 * <p>This class uses Lombok's {@code @Getter} and {@code @Setter} annotations to automatically
 * generate getter and setter methods for its fields.
 */
@Setter
@Getter
public class Appointment {

  private Long appointmentId; // Auto-generated by the database
  private Long providerId; // Unique to each client
  private Long userId;
  private LocalDateTime startDateTime;
  private LocalDateTime endDateTime;
  private String status;
  private String serviceType;
  private String comments;
}
