runtime: java17
instance_class: F1
env: standard

handlers:
  - url: /.*
    script: this field is required, but ignored

# Environment variables to connect to Cloud SQL
env_variables:
  DB_USER: root1                          # MySQL root username
  DB_PASS: coms4156                      # MySQL root password (set to coms4156)
  DB_NAME: coms4156-db                        # Database you want to use, in this case, "mysql"
  DB_HOST: 127.0.0.1                     # Host for Cloud SQL Proxy

beta_settings:
  cloud_sql_instances: coms4156-436119:us-east1:coms4156
